// app/layout.jsx or app/RootLayout.jsx
import "./globals.css";
import LayoutContent from "./LayoutContent";
import ReduxProvider from "./ReduxProvider"; // ✅ Use the client wrapper

export const metadata = {
  title: "Redux",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          <LayoutContent>{children}</LayoutContent>
        </ReduxProvider>
      </body>
    </html>
  );
}
